### ISSUE TITLE
Lily interpreter locks up when instantiating a class with a constructor taking an optional parameter.

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#262] opened 2016-07-22 21:06 UTC
This code appears to lock up the lily (867d7f40b2b78342d0ce3468167ed871907e448f) interpreter:

    class Test(value: *Integer = 10) {
    	define output {
    		print(value)
    	}
    }

    var test = Test()

On OS X 10.11.6 it will run for at least 30+ seconds:

    $ time ../build/lily lockup.lly 
    ^C

    real	0m33.957s
    user	0m29.831s
    sys	0m1.835s
    $

I'm unsure if it eventually finishes executing. Haven't let it run for more than about 30 seconds.

It showed the same behaviour on Ubuntu Linux 16.04.

**Comment by jesserayadkins** [comment] 2016-07-22 21:26
Hey, that's a name that I haven't seen in a while. As for this bug, I think it's a duplicate of what #183 is talking about (optional arguments and closures don't mix well). But just in case it's not, I'm going to leave this open for the time being.

**Closed** 2016-07-22 22:14 UTC
