### ISSUE TITLE
Segfault when raising an exception using an enum variant instead of a class.

### ISSUE THREAD

**Issue by a-p-** [jesserayadkins/lily#240] opened 2016-07-11 19:06 UTC
Hello,

Raising an exception using an enum variant instead of a class appears to cause lily (7d5e498b53f38ac8df76ca8672471799a741447b) to segfault:

    enum Test {
        Test0
        Test1
    }

    raise Test0()

On OS X 10.11.5, assuming the code is in a file named `raise-enum-variant.lly`:

    $ ../build/lily raise-enum-variant.lly 
    Segmentation fault: 11
    $ 

LLDB shows:

    (lldb) run
    Process 62587 launched: '../build/lily' (x86_64)
    Process 62587 stopped
    * thread #1: tid = 0x1dd823, 0x000000010000a7a7 lily`begin_call(emit=0x0000000100301090, ast=0x0000000100300610) + 551 at lily_emitter.c:3570, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x200010840)
        frame #0: 0x000000010000a7a7 lily`begin_call(emit=0x0000000100301090, ast=0x0000000100300610) + 551 at lily_emitter.c:3570
       3567	    if (call_type == NULL)
       3568	        call_type = ((lily_sym *)call_item)->type;
       3569	
    -> 3570	    if (call_type->cls->id != SYM_CLASS_FUNCTION &&
       3571	        first_tt != tree_variant)
       3572	        lily_raise_adjusted(emit->raiser, ast->line_num, lily_SyntaxError,
       3573	                "Cannot anonymously call resulting type '^T'.\n",
    (lldb) bt
    * thread #1: tid = 0x1dd823, 0x000000010000a7a7 lily`begin_call(emit=0x0000000100301090, ast=0x0000000100300610) + 551 at lily_emitter.c:3570, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x200010840)
      * frame #0: 0x000000010000a7a7 lily`begin_call(emit=0x0000000100301090, ast=0x0000000100300610) + 551 at lily_emitter.c:3570
        frame #1: 0x000000010000a09b lily`eval_variant(emit=0x0000000100301090, ast=0x0000000100300610, expect=0x0000000000000000) + 203 at lily_emitter.c:3709
        frame #2: 0x0000000100007d85 lily`eval_call(emit=0x0000000100301090, ast=0x0000000100300610, expect=0x0000000000000000) + 69 at lily_emitter.c:3668
        frame #3: 0x000000010000599d lily`eval_tree(emit=0x0000000100301090, ast=0x0000000100300610, expect=0x0000000000000000) + 333 at lily_emitter.c:3816
        frame #4: 0x00000001000055b9 lily`eval_enforce_value(emit=0x0000000100301090, ast=0x0000000100300610, expect=0x0000000000000000, message="'raise' expression has no value.\n") + 41 at lily_emitter.c:3891
        frame #5: 0x0000000100006583 lily`lily_emit_raise(emit=0x0000000100301090, es=0x0000000100300550) + 51 at lily_emitter.c:4058
        frame #6: 0x0000000100019f87 lily`raise_handler(parser=0x0000000100300300, multi=1) + 103 at lily_parser.c:3452
        frame #7: 0x0000000100018f3a lily`statement(parser=0x0000000100300300, multi=1) + 106 at lily_parser.c:2784
        frame #8: 0x0000000100014631 lily`parser_loop(parser=0x0000000100300300, filename="raise-enum-variant.lly") + 65 at lily_parser.c:4115
        frame #9: 0x0000000100014583 lily`lily_parse_file(parser=0x0000000100300300, mode=lm_no_tags, filename="raise-enum-variant.lly") + 195 at lily_parser.c:4197
        frame #10: 0x0000000100001318 lily`main(argc=2, argv=0x00007fff5fbff9a8) + 232 at lily.c:97
        frame #11: 0x00007fff84b745ad libdyld.dylib`start + 1
        frame #12: 0x00007fff84b745ad libdyld.dylib`start + 1
    (lldb) 

And under Ubuntu Linux 16.04:

    $ ./lily raise-enum-variant.lly 
    Segmentation fault (core dumped)
    $

GDB shows:

    (gdb) run raise-enum-variant.lly
    Starting program: /home/user/lily/lily raise-enum-variant.lly

    Program received signal SIGSEGV, Segmentation fault.
    0x000000000042c4dc in begin_call (emit=0x6410b0, ast=0x640400) at /home/user/lily/src/lily_emitter.c:3570
    3570	    if (call_type->cls->id != SYM_CLASS_FUNCTION &&
    (gdb) bt
    #0  0x000000000042c4dc in begin_call (emit=0x6410b0, ast=0x640400) at /home/user/lily/src/lily_emitter.c:3570
    #1  0x000000000042ca0d in eval_variant (emit=0x6410b0, ast=0x640400, expect=0x0) at /home/user/lily/src/lily_emitter.c:3709
    #2  0x000000000042c896 in eval_call (emit=0x6410b0, ast=0x640400, expect=0x0) at /home/user/lily/src/lily_emitter.c:3668
    #3  0x000000000042cda3 in eval_tree (emit=0x6410b0, ast=0x640400, expect=0x0) at /home/user/lily/src/lily_emitter.c:3816
    #4  0x000000000042d1c8 in eval_enforce_value (emit=0x6410b0, ast=0x640400, expect=0x0, message=0x437430 "'raise' expression has no value.\n")
        at /home/user/lily/src/lily_emitter.c:3891
    #5  0x000000000042d76b in lily_emit_raise (emit=0x6410b0, es=0x640310) at /home/user/lily/src/lily_emitter.c:4058
    #6  0x000000000040dc83 in raise_handler (parser=0x640070, multi=1) at /home/user/lily/src/lily_parser.c:3452
    #7  0x000000000040be73 in statement (parser=0x640070, multi=1) at /home/user/lily/src/lily_parser.c:2784
    #8  0x000000000040fa9c in parser_loop (parser=0x640070, filename=0x7fffffffe2f7 "raise-enum-variant.lly") at /home/user/lily/src/lily_parser.c:4115
    #9  0x000000000040fe00 in lily_parse_file (parser=0x640070, mode=lm_no_tags, filename=0x7fffffffe2f7 "raise-enum-variant.lly") at /home/user/lily/src/lily_parser.c:4197
    #10 0x0000000000405ea7 in main (argc=2, argv=0x7fffffffdf68) at /home/user/lily/run/lily.c:97
    (gdb)

**Comment by jesserayadkins** [comment] 2016-07-12 02:07
Closing this as a duplicate of #239. Both have the same root cause of the parser not verifying that the class extends from Exception. Enums can't inherit from a class, so solving #239 will solve this as well.

I do appreciate what you're doing, by the way. The more bugs that are ironed out now, the better that Lily will be when it hits 1.0.

**Closed by jesserayadkins** 2016-07-12 02:07 UTC
