### ISSUE TITLE
Probable miscompile with nested functions

### ISSUE THREAD

**Issue by stevedonovan** [jesserayadkins/lily#257] opened 2016-07-14 13:01 UTC
The nested `collect_while` function misbehaves, and we get
```
$ lily nested-bug1.lly
before: h
before: l
before: o
before:  
after: []
```
Looks very much like a misplaced back jump!

```python
# nested-bug1.lly
define dbg[A](msg: String, val: A) {
   print($"^(msg): ^(val)")
}

define test(str: String) {
   var i = -1
   var ch = ""
   define get: String {
      var res = ch
      i += 1
      ch = str[i]
      return res
   }

   define collect_while: String {
      get()
      var ls: List[String] = []
      dbg("before",ch)
      while ch.is_alpha():
         ls.push(get())
      dbg("after",ls)
      return ls.join("")
   }

   print(collect_while())
}

test("hello  ")
```

**Comment by jesserayadkins** [comment] 2016-07-14 19:57
I vaguely remember that there was some problem with closures and setting jumps back up. I need to do some work later on with redoing closures, and I'll tackle this as part of that.

**Comment by jesserayadkins** [comment] 2016-07-28 00:24
I've tested this again with e3a7816, and I'm getting this output:

```
before: h
after: ["h", "e", "l", "l", "o"]
hello
```

I think relative jumps may have fixed what problems that were present, but I'm not 100% sure. Do you have any issues relating to blocks and closures still?

**Comment by stevedonovan** [comment] 2016-07-28 06:22
I can confirm that the example is now working, thanks!  Shall we keep this open until we're sure of other cases?

**Comment by stevedonovan** [comment] 2016-07-28 06:24
This variant still gives trouble:

```python
define dbg[A](msg: String, val: A) {
   print($"^(msg): ^(val)")
}

define test(str: String) {
   var i = -1
   var ch = ""
   define get: String {
      var res = ch
      i += 1
      ch = str[i]
      return res
   }

   define collect_while: String {
      get()
      var ls: List[String] = []
      dbg("before",ch)
      while ch.is_alpha():
         ls.push(get())
      dbg("after",ls)
      return ls.join("")
   }
   print(collect_while())
}
test("hello  ")
before: h
IndexError: Index 5 is out of range.
Traceback:
    from lambda-bug1.lly:8: in (lambda)
    from lambda-bug1.lly:21: in (lambda)
    from lambda-bug1.lly:26: in test
    from lambda-bug1.lly:30: in __main__


```

**Comment by stevedonovan** [comment] 2016-07-28 11:18
My apologies - a mispaste. Replace that `define` (which does work) with this lambda equivalent:
```
   var collect_while = {||
      get()
      var ls: List[String] = []
      dbg("before",ch)
      while ch.is_alpha():
         ls.push(get())
      dbg("after",ls)
      ls.join("")
   }
```

**Comment by jesserayadkins** [comment] 2016-07-28 19:15
What's strange is that this is working for a define block, but not a lambda block. I can't imagine what's internally different enough between those blocks to break this. Even worse, I can't reproduce this on my machine. Are you using a 32-bit machine for this (grasping for a straw there). Assuming that's not the case, I'm wondering if there's bad code gen involved.

What happens if you edit `get` to print out `i` each pass, for both the lambda and non-lambda versions?

**Comment by stevedonovan** [comment] 2016-07-29 06:23
Ah, I see the problem - I tested with the string "hello" and it simply ran out of string while testing. It works with "hello ". Just code that doesn't check for an obvious error condition - C teaches us bad habits, one of which is that there's always a char after the end of a string ;)

**Comment by stevedonovan** [comment] 2016-07-29 06:26
The Bug du Jour is an interesting one. I've implemented a simplified `format` function in xstr. (see end of it in https://gist.github.com/stevedonovan/71b1e2443602edee308aab07e233854b)
```python
$ cat value-vararg-bug1.lly 
import xstr
var s = "hello"
print(xstr.format("[{}]",s.upper()))
$ lily value-vararg-bug1.lly
HELLO
```
It does work if you just pass a variable!  My friend GDB informs me that the first `fmt` arg of `xstr.format` was "HELLO" - the value of the string! The varargs are ["HELLO"] as expected.

**Comment by jesserayadkins** [comment] 2016-07-29 07:18
I'm glad to hear that the original issue is fixed. I was worried for a moment that we'd have to play hot potato passing messages between each other trying to figure it out.

What you're running into is almost certainly an emitter bug (more specifically, a storage is likely being used again that shouldn't be). I'll see if I can push a fix soon, and then I'll close this bug as a whole.

**Closed** 2016-07-29 07:34 UTC
Labels: Bug
